podTemplate(yaml: """\
    apiVersion: v1
    kind: Pod
    spec:
      containers:
      - name: alpine
        image: alpine
        command:
        - sleep
        - infinity
    """.stripIndent()) {
    node(POD_LABEL) {
      container('alpine') {
        stage("Prepare"){
          checkout scm
        }

        stage("Preparation"){
          sh"""
          apk update && apk add curl
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/\$(curl -s \\
            https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          ./kubectl get po
          """
        }
      }
    }
}
